#!/bin/bash

echo generate simple web app

mvn archetype:generate \
	-DgroupId=$2 \
	-DartifactId=$1 \
	-DarchetypeGroupId=org.apache.maven.archetypes \
	-DarchetypeArtifactId=maven-archetype-webapp \
	-DarchetypeVersion=1.3 \
	-DinteractiveMode=false
